// This file is @generated by prost-build.
/// Protocol message body
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolMessage {
    /// Protocol version, e.g. "1.0"
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Message type
    #[prost(enumeration = "MessageType", tag = "2")]
    pub r#type: i32,
    /// Unique message identifier
    #[prost(string, tag = "3")]
    pub id: ::prost::alloc::string::String,
    /// Timestamp
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Sender identifier
    #[prost(string, tag = "5")]
    pub source: ::prost::alloc::string::String,
    /// Receiver identifier
    #[prost(string, tag = "6")]
    pub target: ::prost::alloc::string::String,
    /// The following fields are used selectively based on type
    ///
    /// Method type (used for requests)
    #[prost(enumeration = "Method", optional, tag = "7")]
    pub method: ::core::option::Option<i32>,
    /// Parameters (used for requests/notifications)
    #[prost(message, optional, tag = "8")]
    pub params: ::core::option::Option<::prost_types::Any>,
    /// Result (used for responses)
    #[prost(message, optional, tag = "9")]
    pub result: ::core::option::Option<::prost_types::Any>,
    /// Error information (used for error responses)
    #[prost(message, optional, tag = "10")]
    pub error: ::core::option::Option<ErrorInfo>,
    /// Extension fields
    ///
    /// Metadata
    #[prost(map = "string, string", tag = "15")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Error information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorInfo {
    /// error code
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// error message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// additional error details
    #[prost(message, optional, tag = "3")]
    pub details: ::core::option::Option<::prost_types::Struct>,
}
/// Plugin initialization
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializeRequest {
    /// Plugin configuration
    #[prost(message, optional, tag = "1")]
    pub plugin_config: ::core::option::Option<::prost_types::Struct>,
    /// Broker information
    #[prost(message, optional, tag = "2")]
    pub broker_info: ::core::option::Option<BrokerInfo>,
    /// Required capabilities
    #[prost(string, repeated, tag = "3")]
    pub required_capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializeResponse {
    /// Status: "ready", "error"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// Capabilities provided by the plugin
    #[prost(string, repeated, tag = "2")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Registered hooks
    #[prost(message, repeated, tag = "3")]
    pub hooks: ::prost::alloc::vec::Vec<Hook>,
    /// Plugin information
    #[prost(message, optional, tag = "4")]
    pub plugin_info: ::core::option::Option<::prost_types::Struct>,
    /// Authentication code for plugin registration
    #[prost(string, tag = "5")]
    pub auth_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BrokerInfo {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub node_id: i32,
    #[prost(string, tag = "3")]
    pub cluster_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub properties: ::core::option::Option<::prost_types::Struct>,
}
/// Hook definition
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hook {
    /// Hook name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Priority (0-1000)
    #[prost(uint32, tag = "2")]
    pub priority: u32,
    /// Filter conditions
    #[prost(message, optional, tag = "3")]
    pub filter: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticateRequest {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub client_ip: ::prost::alloc::string::String,
    /// Client certificate
    #[prost(bytes = "vec", tag = "5")]
    pub client_cert: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "6")]
    pub protocol_version: ::prost::alloc::string::String,
    /// MQTT 5.0 properties
    #[prost(message, optional, tag = "7")]
    pub properties: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticateResponse {
    /// Authentication result
    #[prost(bool, tag = "1")]
    pub authenticated: bool,
    /// Permission list
    #[prost(string, repeated, tag = "2")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Session data
    #[prost(message, optional, tag = "3")]
    pub session_data: ::core::option::Option<::prost_types::Struct>,
    /// Failure reason
    #[prost(string, optional, tag = "4")]
    pub error_reason: ::core::option::Option<::prost::alloc::string::String>,
    /// Tenant ID
    #[prost(string, optional, tag = "5")]
    pub tenant_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizeRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    /// Action type
    #[prost(enumeration = "AuthAction", tag = "4")]
    pub action: i32,
    /// Topic
    #[prost(string, tag = "5")]
    pub topic: ::prost::alloc::string::String,
    /// QoS level
    #[prost(uint32, tag = "6")]
    pub qos: u32,
    /// Context information
    #[prost(message, optional, tag = "7")]
    pub context: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizeResponse {
    #[prost(bool, tag = "1")]
    pub authorized: bool,
    /// Denial reason
    #[prost(string, optional, tag = "2")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    /// Modified context
    #[prost(message, optional, tag = "3")]
    pub modified_context: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MqttMessage {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// Client ID
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    /// Topic
    #[prost(string, tag = "3")]
    pub topic: ::prost::alloc::string::String,
    /// Payload data
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// QoS level
    #[prost(uint32, tag = "5")]
    pub qos: u32,
    /// Retain flag
    #[prost(bool, tag = "6")]
    pub retain: bool,
    /// Duplicate flag
    #[prost(bool, tag = "7")]
    pub dup: bool,
    /// Publish time
    #[prost(message, optional, tag = "8")]
    pub publish_time: ::core::option::Option<::prost_types::Timestamp>,
    /// MQTT 5.0 properties
    #[prost(message, optional, tag = "9")]
    pub properties: ::core::option::Option<::prost_types::Struct>,
    /// Message ID
    #[prost(string, optional, tag = "10")]
    pub message_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Message publish handling
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePublishRequest {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<MqttMessage>,
    /// Context information
    #[prost(message, optional, tag = "2")]
    pub context: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePublishResponse {
    /// Whether publishing is allowed
    #[prost(bool, tag = "1")]
    pub allow: bool,
    /// Modified message
    #[prost(message, optional, tag = "2")]
    pub modified_message: ::core::option::Option<MqttMessage>,
    /// Denial reason
    #[prost(string, optional, tag = "3")]
    pub error_reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub continue_chain: ::core::option::Option<bool>,
}
/// Subscription handling
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeRequest {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub subscriptions: ::prost::alloc::vec::Vec<TopicFilter>,
    #[prost(message, optional, tag = "3")]
    pub context: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<SubscribeResult>,
    #[prost(bool, optional, tag = "2")]
    pub continue_chain: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicFilter {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub qos: u32,
    /// Subscription options
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeResult {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub allowed: bool,
    #[prost(uint32, tag = "3")]
    pub granted_qos: u32,
    #[prost(string, optional, tag = "4")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
/// Client events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientConnectedEvent {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub protocol_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub connect_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub client_info: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientDisconnectedEvent {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    /// Disconnect reason
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub disconnect_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub session_info: ::core::option::Option<::prost_types::Struct>,
}
/// Statistics information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatsRequest {
    /// Requested metrics
    #[prost(string, repeated, tag = "1")]
    pub metrics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatsResponse {
    #[prost(map = "string, message", tag = "1")]
    pub metrics: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        MetricValue,
    >,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricValue {
    #[prost(oneof = "metric_value::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<metric_value::Value>,
}
/// Nested message and enum types in `MetricValue`.
pub mod metric_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        IntValue(i64),
        #[prost(double, tag = "2")]
        DoubleValue(f64),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "4")]
        StructValue(::prost_types::Struct),
    }
}
/// Health check
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {
    #[prost(string, optional, tag = "1")]
    pub service: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(enumeration = "HealthStatus", tag = "1")]
    pub status: i32,
    #[prost(map = "string, string", tag = "2")]
    pub details: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub check_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchRequest {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<ProtocolMessage>,
    #[prost(bool, tag = "2")]
    pub ordered: bool,
    #[prost(uint32, tag = "3")]
    pub timeout_ms: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchResponse {
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<ProtocolMessage>,
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<ErrorInfo>,
    #[prost(message, optional, tag = "3")]
    pub stats: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginMetadata {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub author: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub config_schema: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, repeated, tag = "7")]
    pub dependencies: ::prost::alloc::vec::Vec<Dependency>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dependency {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version_constraint: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub optional: bool,
}
/// Message type enum
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Unspecified = 0,
    Request = 1,
    Response = 2,
    Notification = 3,
    Event = 4,
    Error = 5,
    BatchRequest = 6,
    BatchResponse = 7,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_TYPE_UNSPECIFIED",
            Self::Request => "MESSAGE_TYPE_REQUEST",
            Self::Response => "MESSAGE_TYPE_RESPONSE",
            Self::Notification => "MESSAGE_TYPE_NOTIFICATION",
            Self::Event => "MESSAGE_TYPE_EVENT",
            Self::Error => "MESSAGE_TYPE_ERROR",
            Self::BatchRequest => "MESSAGE_TYPE_BATCH_REQUEST",
            Self::BatchResponse => "MESSAGE_TYPE_BATCH_RESPONSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_TYPE_REQUEST" => Some(Self::Request),
            "MESSAGE_TYPE_RESPONSE" => Some(Self::Response),
            "MESSAGE_TYPE_NOTIFICATION" => Some(Self::Notification),
            "MESSAGE_TYPE_EVENT" => Some(Self::Event),
            "MESSAGE_TYPE_ERROR" => Some(Self::Error),
            "MESSAGE_TYPE_BATCH_REQUEST" => Some(Self::BatchRequest),
            "MESSAGE_TYPE_BATCH_RESPONSE" => Some(Self::BatchResponse),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Method {
    Unspecified = 0,
    /// Lifecycle management (10-19)
    Initialize = 10,
    Shutdown = 11,
    Ping = 12,
    RegisterPlugin = 13,
    UnregisterPlugin = 14,
    /// Authentication and authorization (20-29)
    Authenticate = 20,
    Authorize = 21,
    GetAcl = 23,
    /// MQTT message handling (30-39)
    OnMessagePublish = 30,
    OnMessageSubscribe = 31,
    OnMessageUnsubscribe = 32,
    /// Event notification (50-59)
    ClientConnected = 50,
    ClientDisconnected = 51,
    MessagePublished = 52,
    SubscriptionAdded = 53,
    SubscriptionRemoved = 54,
    /// Monitoring (60-69)
    GetStats = 60,
    ResetStats = 61,
    HealthCheck = 62,
}
impl Method {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "METHOD_UNSPECIFIED",
            Self::Initialize => "METHOD_INITIALIZE",
            Self::Shutdown => "METHOD_SHUTDOWN",
            Self::Ping => "METHOD_PING",
            Self::RegisterPlugin => "METHOD_REGISTER_PLUGIN",
            Self::UnregisterPlugin => "METHOD_UNREGISTER_PLUGIN",
            Self::Authenticate => "METHOD_AUTHENTICATE",
            Self::Authorize => "METHOD_AUTHORIZE",
            Self::GetAcl => "METHOD_GET_ACL",
            Self::OnMessagePublish => "METHOD_ON_MESSAGE_PUBLISH",
            Self::OnMessageSubscribe => "METHOD_ON_MESSAGE_SUBSCRIBE",
            Self::OnMessageUnsubscribe => "METHOD_ON_MESSAGE_UNSUBSCRIBE",
            Self::ClientConnected => "METHOD_CLIENT_CONNECTED",
            Self::ClientDisconnected => "METHOD_CLIENT_DISCONNECTED",
            Self::MessagePublished => "METHOD_MESSAGE_PUBLISHED",
            Self::SubscriptionAdded => "METHOD_SUBSCRIPTION_ADDED",
            Self::SubscriptionRemoved => "METHOD_SUBSCRIPTION_REMOVED",
            Self::GetStats => "METHOD_GET_STATS",
            Self::ResetStats => "METHOD_RESET_STATS",
            Self::HealthCheck => "METHOD_HEALTH_CHECK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "METHOD_INITIALIZE" => Some(Self::Initialize),
            "METHOD_SHUTDOWN" => Some(Self::Shutdown),
            "METHOD_PING" => Some(Self::Ping),
            "METHOD_REGISTER_PLUGIN" => Some(Self::RegisterPlugin),
            "METHOD_UNREGISTER_PLUGIN" => Some(Self::UnregisterPlugin),
            "METHOD_AUTHENTICATE" => Some(Self::Authenticate),
            "METHOD_AUTHORIZE" => Some(Self::Authorize),
            "METHOD_GET_ACL" => Some(Self::GetAcl),
            "METHOD_ON_MESSAGE_PUBLISH" => Some(Self::OnMessagePublish),
            "METHOD_ON_MESSAGE_SUBSCRIBE" => Some(Self::OnMessageSubscribe),
            "METHOD_ON_MESSAGE_UNSUBSCRIBE" => Some(Self::OnMessageUnsubscribe),
            "METHOD_CLIENT_CONNECTED" => Some(Self::ClientConnected),
            "METHOD_CLIENT_DISCONNECTED" => Some(Self::ClientDisconnected),
            "METHOD_MESSAGE_PUBLISHED" => Some(Self::MessagePublished),
            "METHOD_SUBSCRIPTION_ADDED" => Some(Self::SubscriptionAdded),
            "METHOD_SUBSCRIPTION_REMOVED" => Some(Self::SubscriptionRemoved),
            "METHOD_GET_STATS" => Some(Self::GetStats),
            "METHOD_RESET_STATS" => Some(Self::ResetStats),
            "METHOD_HEALTH_CHECK" => Some(Self::HealthCheck),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuthAction {
    Unspecified = 0,
    Connect = 1,
    Publish = 2,
    Subscribe = 3,
    Unsubscribe = 4,
}
impl AuthAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUTH_ACTION_UNSPECIFIED",
            Self::Connect => "AUTH_ACTION_CONNECT",
            Self::Publish => "AUTH_ACTION_PUBLISH",
            Self::Subscribe => "AUTH_ACTION_SUBSCRIBE",
            Self::Unsubscribe => "AUTH_ACTION_UNSUBSCRIBE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTH_ACTION_UNSPECIFIED" => Some(Self::Unspecified),
            "AUTH_ACTION_CONNECT" => Some(Self::Connect),
            "AUTH_ACTION_PUBLISH" => Some(Self::Publish),
            "AUTH_ACTION_SUBSCRIBE" => Some(Self::Subscribe),
            "AUTH_ACTION_UNSUBSCRIBE" => Some(Self::Unsubscribe),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HealthStatus {
    Unspecified = 0,
    Healthy = 1,
    Unhealthy = 2,
    Degraded = 3,
}
impl HealthStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "HEALTH_STATUS_UNSPECIFIED",
            Self::Healthy => "HEALTH_STATUS_HEALTHY",
            Self::Unhealthy => "HEALTH_STATUS_UNHEALTHY",
            Self::Degraded => "HEALTH_STATUS_DEGRADED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HEALTH_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "HEALTH_STATUS_HEALTHY" => Some(Self::Healthy),
            "HEALTH_STATUS_UNHEALTHY" => Some(Self::Unhealthy),
            "HEALTH_STATUS_DEGRADED" => Some(Self::Degraded),
            _ => None,
        }
    }
}
