syntax = "proto3";

package openraftpb;

enum ErrorCode {
  UNKNOWN = 0;
  INTERNAL_ERROR = 1;
}

service RaftService {

  rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);

  rpc Vote(VoteRequest) returns (VoteResponse);

  rpc InstallSnapshot(InstallSnapshotRequest) returns (InstallSnapshotResponse);

  rpc RoutePacket(RoutePacketRequest) returns (RoutePacketResponse);

  rpc SessionForceDisconnect(ForceSessionDisconnectRequest) returns (ForceSessionDisconnectResponse);

  rpc SessionActorForceStop(SessionActorForceStopRequest) returns (SessionActorForceStopResponse);

  rpc GetSessionActorMap(GetSessionActorMapRequest) returns (GetSessionActorMapResponse);

  rpc GetSessionState(GetSessionStateRequest) returns (GetSessionStateResponse);

  rpc GetSubscriptions(GetSubscriptionRequest) returns (GetSubscriptionResponse);

  rpc SessionStateExisted(SessionExistedRequest) returns (SessionExistedResponse);

  rpc InflightGetCurrentPacket(InflightGetCurrentPacketRequest) returns (InflightGetCurrentPacketResponse);

}

message ErrorDetail {

  ErrorCode code = 1;

  string message = 2;

  string node = 3;

}

message GetSubscriptionRequest {

  string tenant_id = 1;

  string topic = 2;

}

message Subscription {

  uint64 node_id = 1;

  uint32 qos = 2;

  string client_id = 3;

}

message GetSubscriptionResponse {

  bool success = 1;

  ErrorDetail error = 2;

  repeated Subscription subscriptions = 3;

}

message InflightGetCurrentPacketResponse {

  bool success = 1;

  ErrorDetail error = 2;

  optional string packet = 3;
}

message InflightGetCurrentPacketRequest {

  string tenant_id = 1;

  string client_id = 2;

  uint64 packet_id = 3;

}

message SessionActorForceStopResponse {

  bool success = 1;

  ErrorDetail error = 2;

}

message SessionActorForceStopRequest {

  string tenant_id = 1;

  string client_id = 2;

}

message SessionExistedResponse {

  bool success = 1;

  ErrorDetail error = 2;

  bool session_existed = 3;

}

message SessionExistedRequest {
  
  string tenant_id = 1;

  string client_id = 2;

}

message GetSessionStateRequest {
  
  string tenant_id = 1;

  string client_id = 2;

}

message GetSessionStateResponse {

  bool success = 1;

  ErrorDetail error = 2;

  optional string session_state_data = 3;
  
}

message SessionVersion {

  uint64 node_id = 1;

  uint64 counter = 2;
}

message GetSessionActorMapResponse {

  bool success = 1;

  ErrorDetail error = 2;

  optional uint64 node_id = 3;

  optional SessionVersion version = 4;
}

message GetSessionActorMapRequest {
  string tenant_id = 1;
  string client_id = 2;
}

message ForceSessionDisconnectRequest {
  string tenant_id = 1;
  string client_id = 2;
}

message ForceSessionDisconnectResponse {
  bool success = 1;
  ErrorDetail error = 2;
}

message RoutePacketRequest {

  string data = 1;

}

message RoutePacketResponse {

  bool success = 1;

  ErrorDetail error = 2;

  string data = 3;

}

enum RaftType {
  TOPIC = 0;
  SESSION_ACTOR_MAP = 1;
  SESSION_STATE = 2;
}

message AppendEntriesRequest {
  string data = 1;
  RaftType raft_type = 2;
}

message AppendEntriesResponse {
  bool success = 1;

  ErrorDetail error = 2;

  string data = 3;
}

message VoteRequest {
  string data = 1;
  RaftType raft_type = 2;
}

message VoteResponse {
  bool success = 1;

  ErrorDetail error = 2;

  string data = 3;
}

message InstallSnapshotRequest {
  string data = 1;
  RaftType raft_type = 2;
}

message InstallSnapshotResponse {
  bool success = 1;

  ErrorDetail error = 2;

  string data = 3;
}