use std::{collections::HashMap, sync::Arc};

use parking_lot::RwLock;

use base64::{engine::general_purpose, Engine};
use log::warn;
use serde::{Deserialize, Deserializer, Serialize};
use yedmq_mqtt::packet::Packet;

use crate::stored_packet::deserialize_stored_packet;
use crate::topic::TopicStorageError;

pub type TopicPaginationResult = (u64, Vec<(String, String, u8)>);

type RetainMessageMap = HashMap<String, (String, u8)>;
type RetainMessageRecorder = HashMap<String, RetainMessageMap>;

/// Generates a key string that can be used to store subscriptions in a `SubscriptionMap`.
///
/// The key is formatted as "encoded_client_id:encoded_topic:qos", where:
///
/// - `encoded_client_id` is the Base64-encoded client ID.
/// - `encoded_topic` is the Base64-encoded topic.
/// - `qos` is the QoS level.
///
/// # Arguments
///
/// * `client_id` - The client ID.
/// * `topic` - The topic.
/// * `qos` - The QoS level.
///
/// # Returns
///
/// A string slice that can be used as a key in a `SubscriptionMap`.
fn generate_key(client_id: &str, topic: &str) -> String {
    let encoded_client_id = general_purpose::STANDARD.encode(client_id);
    let encoded_topic = general_purpose::STANDARD.encode(topic);
    format!("{}:{}", encoded_client_id, encoded_topic)
}

/// Extracts and decodes information from a key.
///
/// This function takes a key string formatted as "encoded_client_id:encoded_topic:qos",
/// splits it into parts, and decodes the client ID and topic using Base64 decoding.
/// It returns a tuple containing the decoded client ID, decoded topic, and the QoS level.
///
/// # Arguments
///
/// * `key` - A string slice that holds the key in the format "encoded_client_id:encoded_topic:qos"
///
/// # Returns
///
/// * A tuple containing:
///   - `String`: Decoded client ID
///   - `String`: Decoded topic
///   - `u8`: QoS level
///
/// # Panics
///
/// This function will panic if the Base64 decoding fails or if the QoS level cannot be parsed as a `u8`.
fn extract_info_from_key(key: &str) -> (String, String) {
    let i = key.split(":");
    let mut index = 0;
    let mut encoded_client_id = String::new();
    let mut encoded_topic = String::new();
    for s in i {
        index += 1;
        if index == 1 {
            encoded_client_id = s.to_string();
        } else if index == 2 {
            encoded_topic = s.to_string();
        }
    }
    let binding = general_purpose::STANDARD
        .decode(&encoded_client_id)
        .expect("key must be generated by generate_key method");
    let client_id =
        std::str::from_utf8(&binding).expect("key must be generated by generate_key method");
    let binding = general_purpose::STANDARD
        .decode(&encoded_topic)
        .expect("key must be generated by generate_key method");
    let topic =
        std::str::from_utf8(&binding).expect("key must be generated by generate_key method");
    (client_id.to_string(), topic.to_string())
}

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct Subscription {
    pub client_identifier: String,
    pub qos: u8,
    #[serde(default)]
    pub no_local: bool,
    #[serde(default)]
    pub retain_as_published: bool,
}

#[derive(Debug, Serialize, Deserialize)]
struct TopicStorageNode {
    pub topic_parttern: String,

    subscriptions: RwLock<HashMap<String, Arc<Subscription>>>,

    retain_publish_packet: Option<Arc<Packet>>,

    leaves: Arc<RwLock<HashMap<String, Arc<RwLock<TopicStorageNode>>>>>,
}

impl TopicStorageNode {
    fn to_serializable(&self) -> SerializableTopicStorageNode {
        SerializableTopicStorageNode {
            topic_parttern: self.topic_parttern.clone(),
            subscriptions: self
                .subscriptions
                .read()
                .iter()
                .map(|(k, v)| (k.clone(), (**v).clone()))
                .collect(),
            retain_publish_packet: self.retain_publish_packet.as_ref().map(|p| (**p).clone()),
            leaves: self
                .leaves
                .read()
                .iter()
                .map(|(k, v)| (k.clone(), v.read().to_serializable()))
                .collect(),
        }
    }

    fn from_serializable(data: SerializableTopicStorageNode) -> Self {
        TopicStorageNode {
            topic_parttern: data.topic_parttern,
            subscriptions: RwLock::new(
                data.subscriptions
                    .into_iter()
                    .map(|(k, v)| (k, Arc::new(v)))
                    .collect(),
            ),
            retain_publish_packet: data.retain_publish_packet.map(Arc::new),
            leaves: Arc::new(RwLock::new(
                data.leaves
                    .into_iter()
                    .map(|(k, v)| {
                        (
                            k,
                            Arc::new(RwLock::new(TopicStorageNode::from_serializable(v))),
                        )
                    })
                    .collect(),
            )),
        }
    }

    pub fn new(topic_pattern: String) -> Self {
        TopicStorageNode {
            topic_parttern: topic_pattern,
            subscriptions: RwLock::new(HashMap::new()),
            retain_publish_packet: None,
            leaves: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    pub fn add_subscription(&self, subscribtion: Subscription) {
        self.subscriptions.write().insert(
            subscribtion.client_identifier.clone(),
            Arc::new(subscribtion),
        );
    }

    pub fn get_subscriptions(&self) -> Vec<Arc<Subscription>> {
        let mut out = Vec::with_capacity(self.subscriptions.read().len());
        for (_, subscribtion) in self.subscriptions.read().iter() {
            out.push(Arc::clone(subscribtion));
        }
        out
    }

    pub fn set_retain_publish_message(&mut self, publish_packet: Packet) {
        self.retain_publish_packet = Some(Arc::new(publish_packet));
    }

    pub fn clean_retain_publish_message(&mut self) {
        self.retain_publish_packet = None;
    }

    pub fn remove_subscription(&self, client_identifier: &str) {
        let client_existed = self.subscriptions.read().contains_key(client_identifier);

        if client_existed {
            self.subscriptions.write().remove(client_identifier);
        }
    }

    fn get_leaf(&self, topic_pattern: String) -> Option<Arc<RwLock<TopicStorageNode>>> {
        let sub_leaf_existed = self.leaves.read().contains_key(&topic_pattern);

        if sub_leaf_existed {
            return Some(Arc::clone(&self.leaves.read()[&topic_pattern]));
        } else {
            None
        }
    }

    fn find_or_create_leaf(&self, topic_pattern: String) -> Arc<RwLock<TopicStorageNode>> {
        let sub_leaf_existed = self.leaves.read().contains_key(&topic_pattern);

        if sub_leaf_existed {
            return Arc::clone(&self.leaves.read()[&topic_pattern]);
        } else {
            let leaf = Arc::new(RwLock::new(TopicStorageNode {
                topic_parttern: topic_pattern.clone(),
                subscriptions: RwLock::new(HashMap::new()),
                leaves: Arc::new(RwLock::new(HashMap::new())),
                retain_publish_packet: None,
            }));
            let topic_node_cloned = leaf.clone();
            self.leaves.write().insert(topic_pattern, leaf.clone());
            topic_node_cloned
        }
    }
}

#[derive(Debug)]
pub struct TopicStorage {
    retain_message_recorder: RwLock<RetainMessageRecorder>,

    topic_info_recorder: RwLock<HashMap<String, HashMap<String, u8>>>,

    topic_tree: Arc<RwLock<HashMap<String, Arc<RwLock<TopicStorageNode>>>>>,
}

fn test_topic(topic: &str) -> bool {
    let i = topic.split("/");
    let mut index = 0;
    let length = i.clone().count();
    for s in i {
        index += 1;
        if s.len() > 1 {
            if s.contains('#') || s.contains('+') {
                return false;
            }
        } else if s.contains('#') && index != length {
            return false;
        }
    }
    true
}

impl Default for TopicStorage {
    fn default() -> Self {
        Self::new()
    }
}

impl TopicStorage {
    pub fn get_retain_message_list_with_pagination(
        &self,
        tenant_identifier: &str,
        offset: u64,
        limit: u64,
    ) -> Result<TopicPaginationResult, TopicStorageError> {
        if !self
            .retain_message_recorder
            .read()
            .contains_key(tenant_identifier)
        {
            Err(TopicStorageError::TenantNotFound(
                tenant_identifier.to_string(),
            ))
        } else {
            let retain_message_recorder = self.retain_message_recorder.read();
            match retain_message_recorder.get(tenant_identifier) {
                Some(retain_message_list) => {
                    let total = retain_message_list.len() as u64;
                    let result: Vec<(String, String, u8)> = retain_message_list
                        .iter()
                        .skip(offset as usize)
                        .take(limit as usize)
                        .map(|(topic_filter, (client_id, qos))| {
                            (topic_filter.clone(), client_id.clone(), *qos)
                        })
                        .collect();
                    Ok((total, result))
                }
                None => Ok((0, vec![])),
            }
        }
    }

    pub fn get_topic_list_with_pagination(
        &self,
        tenant_id: &str,
        offset: u64,
        limit: u64,
    ) -> Result<TopicPaginationResult, TopicStorageError> {
        let topic_info_recorder = self.topic_info_recorder.read();
        match topic_info_recorder.get(tenant_id) {
            Some(items) => {
                let result_items: Vec<(String, String, u8)> = items
                    .iter()
                    .skip(offset as usize)
                    .take(limit as usize)
                    .map(|(key, qos)| {
                        let (client_id, topic) = extract_info_from_key(key);
                        (client_id, topic, *qos)
                    })
                    .collect();
                let total = items.len();
                Ok((total as u64, result_items))
            }
            None => Err(TopicStorageError::TenantNotFound(tenant_id.to_string())),
        }
    }

    pub fn contains_tenant(&self, tenant_id: &String) -> bool {
        let topic_tree = self.topic_tree.clone();
        let topic_tree = topic_tree.read();
        topic_tree.contains_key(tenant_id)
    }

    pub fn to_snapshot(&self) -> Result<Vec<u8>, serde_json::Error> {
        let serializable = self.to_serializable();
        serde_json::to_vec(&serializable)
    }

    pub fn from_snapshot(snapshot: Vec<u8>) -> Result<Self, serde_json::Error> {
        let serializable: SerializableTopicStorage = serde_json::from_slice(&snapshot)?;
        Ok(Self::from_serializable(serializable))
    }

    fn to_serializable(&self) -> SerializableTopicStorage {
        SerializableTopicStorage {
            retain_message_recorder: self.retain_message_recorder.read().clone(),
            topic_info_recorder: self.topic_info_recorder.read().clone(),
            topic_tree: self
                .topic_tree
                .read()
                .iter()
                .map(|(k, v)| (k.clone(), v.read().to_serializable()))
                .collect(),
        }
    }

    fn from_serializable(data: SerializableTopicStorage) -> Self {
        TopicStorage {
            retain_message_recorder: RwLock::new(data.retain_message_recorder),
            topic_info_recorder: RwLock::new(data.topic_info_recorder),
            topic_tree: Arc::new(RwLock::new(
                data.topic_tree
                    .into_iter()
                    .map(|(k, v)| {
                        (
                            k,
                            Arc::new(RwLock::new(TopicStorageNode::from_serializable(v))),
                        )
                    })
                    .collect(),
            )),
        }
    }

    pub fn new() -> Self {
        let instance = Self {
            retain_message_recorder: RwLock::new(HashMap::new()),
            topic_info_recorder: RwLock::new(HashMap::new()),
            topic_tree: Arc::new(RwLock::new(HashMap::new())),
        };
        instance.create_tenant(&"public".to_string()); //create default tenant
        instance
    }

    pub fn create_tenant(&self, tenant: &String) {
        let topic_tree = self.topic_tree.clone();
        let mut topic_tree = topic_tree.write();
        if !topic_tree.contains_key(tenant) {
            topic_tree.insert(
                tenant.clone(),
                Arc::new(RwLock::new(TopicStorageNode::new("/".to_string()))),
            );
        }

        let mut topic_info_recorder = self.topic_info_recorder.write();
        if !topic_info_recorder.contains_key(tenant) {
            topic_info_recorder.insert(tenant.clone(), HashMap::new());
        }

        let mut retain_message_recorder = self.retain_message_recorder.write();
        if !retain_message_recorder.contains_key(tenant) {
            retain_message_recorder.insert(tenant.clone(), HashMap::new());
        }
    }

    pub fn subscribe(
        &self,
        tenant_id: String,
        client_identifier: String,
        topic_filter: String,
        qos: u8,
    ) -> Result<(), TopicStorageError> {
        self.subscribe_with_options(
            tenant_id,
            client_identifier,
            topic_filter,
            qos,
            false,
            false,
        )
    }

    pub fn subscribe_with_options(
        &self,
        tenant_id: String,
        client_identifier: String,
        topic_filter: String,
        qos: u8,
        no_local: bool,
        retain_as_published: bool,
    ) -> Result<(), TopicStorageError> {
        if !test_topic(&topic_filter) {
            return Err(TopicStorageError::InvalidTopicFilter(topic_filter));
        }

        let topic_patterns: Vec<String> = topic_filter.split("/").map(String::from).collect();
        let map = self.topic_tree.clone();
        let tenant_topic_root_rwlock = map.read();
        if let Some(tenant_topic_root) = tenant_topic_root_rwlock.get(&tenant_id) {
            let result = Self::recursion_subscribe(
                tenant_topic_root.clone(),
                topic_patterns,
                client_identifier.clone(),
                qos,
                no_local,
                retain_as_published,
            );
            if let Err(err) = result {
                Err(err)
            } else {
                // Update the topic_info_recorder
                let mut topic_info_recorder = self.topic_info_recorder.write();
                if let Some(topic_info_state_item) = topic_info_recorder.get_mut(&tenant_id) {
                    let key = generate_key(&client_identifier, &topic_filter);
                    topic_info_state_item.entry(key).or_insert(qos);
                }
                //

                Ok(())
            }
        } else {
            Err(TopicStorageError::TenantNotFound(tenant_id))
        }
    }

    fn recursion_subscribe(
        topic_node: Arc<RwLock<TopicStorageNode>>,
        mut topic_partterns: Vec<String>,
        client_identifier: String,
        qos: u8,
        no_local: bool,
        retain_as_published: bool,
    ) -> Result<(), TopicStorageError> {
        if !topic_partterns.is_empty() {
            let topic_pattern = &topic_partterns[0];
            let topic_node_next = topic_node
                .write()
                .find_or_create_leaf(topic_pattern.to_string());
            let topic_patterns_rest = topic_partterns.drain(1..).collect();
            Self::recursion_subscribe(
                topic_node_next,
                topic_patterns_rest,
                client_identifier,
                qos,
                no_local,
                retain_as_published,
            )
        } else {
            topic_node.write().add_subscription(Subscription {
                client_identifier,
                qos,
                no_local,
                retain_as_published,
            });
            Ok(())
        }
    }

    pub fn unsubscribe(
        &self,
        tenant_id: &str,
        client_identifier: &str,
        topic_filter: &str,
    ) -> Result<(), TopicStorageError> {
        let topic_patterns: Vec<String> = topic_filter.split("/").map(String::from).collect();
        let map = self.topic_tree.clone();
        let tenant_topic_root_rwlock = map.read();
        if let Some(tenant_topic_root) = tenant_topic_root_rwlock.get(tenant_id) {
            let result = Self::recursion_unsubscription(
                tenant_topic_root.clone(),
                topic_patterns,
                client_identifier,
            );
            if let Err(err) = result {
                Err(err)
            } else {
                // Update the topic_info_recorder
                let mut topic_info_recorder = self.topic_info_recorder.write();
                if let Some(topic_info_state_item) = topic_info_recorder.get_mut(tenant_id) {
                    let key = generate_key(client_identifier, topic_filter);
                    topic_info_state_item.remove(&key);
                }
                //
                Ok(())
            }
        } else {
            Err(TopicStorageError::TenantNotFound(tenant_id.to_string()))
        }
    }

    fn recursion_unsubscription(
        topic_node: Arc<RwLock<TopicStorageNode>>,
        mut topic_partterns: Vec<String>,
        client_identifier: &str,
    ) -> Result<(), TopicStorageError> {
        if !topic_partterns.is_empty() {
            let topic_pattern = &topic_partterns[0];
            let topic_node_next = topic_node.write().get_leaf(topic_pattern.to_string());
            if let Some(topic_node_next) = topic_node_next {
                let topic_patterns_rest = topic_partterns.drain(1..).collect();
                Self::recursion_unsubscription(
                    topic_node_next,
                    topic_patterns_rest,
                    client_identifier,
                )
            } else {
                Err(TopicStorageError::TopicNotFound(topic_pattern.to_string()))
            }
        } else {
            topic_node.write().remove_subscription(client_identifier);
            Ok(())
        }
    }

    pub fn get_subscriptions(
        &self,
        tenant_id: String,
        msg_topic: String,
    ) -> Result<Vec<Arc<Subscription>>, TopicStorageError> {
        let topic_patterns: Vec<String> = msg_topic.split("/").map(String::from).collect();
        let map = self.topic_tree.clone();
        let tenant_topic_root_rwlock = map.read();
        let tenant_topic_root_optional = tenant_topic_root_rwlock.get(&tenant_id);
        if let Some(tenant_topic_root) = tenant_topic_root_optional {
            Ok(Self::recursion_get_subscriptions(
                tenant_topic_root.clone(),
                topic_patterns,
            ))
        } else {
            Err(TopicStorageError::TenantNotFound(tenant_id))
        }
    }

    fn recursion_get_subscriptions(
        topic_node: Arc<RwLock<TopicStorageNode>>,
        mut topic_partterns: Vec<String>,
    ) -> Vec<Arc<Subscription>> {
        if !topic_partterns.is_empty() {
            let mut result = vec![];
            // Get # wildcard subscriptions
            let topic_sharp_wildcard_option = topic_node.read().get_leaf("#".to_string());
            if let Some(topic_sharp_wildcard) = topic_sharp_wildcard_option {
                let sharp_wildcard_subscriptions = topic_sharp_wildcard.read().get_subscriptions();
                result.extend(sharp_wildcard_subscriptions);
            }
            // Get + wildcard subscriptions
            let topic_plus_wildcard_option = topic_node.read().get_leaf("+".to_string());
            if let Some(topic_plus_wildcard) = topic_plus_wildcard_option {
                let mut topic_plus_left = topic_partterns.clone();
                let topic_plus_patterns_rest = topic_plus_left.drain(1..).collect();
                let topic_node_clone = topic_plus_wildcard.clone();
                let plus_wildcard_subscriptions =
                    Self::recursion_get_subscriptions(topic_node_clone, topic_plus_patterns_rest);
                result.extend(plus_wildcard_subscriptions);
            }

            let topic_pattern = &topic_partterns[0];
            let topic_node_next = topic_node.read().get_leaf(topic_pattern.to_string());
            if let Some(topic_node_next) = topic_node_next {
                let topic_patterns_rest = topic_partterns.drain(1..).collect();
                let subscriptions =
                    Self::recursion_get_subscriptions(topic_node_next, topic_patterns_rest);
                result.extend(subscriptions);
            }
            result
        } else {
            topic_node.read().get_subscriptions()
        }
    }

    fn recursion_retain_publish_packet(
        topic_node: Arc<RwLock<TopicStorageNode>>,
        mut topic_partterns: Vec<String>,
        publish_packet: Packet,
    ) -> Result<(), TopicStorageError> {
        if !topic_partterns.is_empty() {
            let topic_pattern = &topic_partterns[0];
            let topic_node_next = topic_node
                .write()
                .find_or_create_leaf(topic_pattern.to_string());
            let topic_patterns_rest = topic_partterns.drain(1..).collect();
            Self::recursion_retain_publish_packet(
                topic_node_next,
                topic_patterns_rest,
                publish_packet,
            )
        } else {
            topic_node
                .write()
                .set_retain_publish_message(publish_packet);
            Ok(())
        }
    }

    fn recursion_clean_retain_publish_packet(
        topic_node: Arc<RwLock<TopicStorageNode>>,
        mut topic_partterns: Vec<String>,
    ) -> Result<(), TopicStorageError> {
        if !topic_partterns.is_empty() {
            let topic_pattern = &topic_partterns[0];
            let topic_node_next = topic_node.write().get_leaf(topic_pattern.to_string());
            if let Some(topic_node_next) = topic_node_next {
                let topic_patterns_rest = topic_partterns.drain(1..).collect();
                Self::recursion_clean_retain_publish_packet(topic_node_next, topic_patterns_rest)
            } else {
                Err(TopicStorageError::TopicNotFound(topic_pattern.to_string()))
            }
        } else {
            topic_node.write().clean_retain_publish_message();
            Ok(())
        }
    }

    // clean retain publish packet from the topic tree
    pub fn clean_retain_publish_packet(
        &self,
        tenant_id: String,
        topic_filter: &String,
    ) -> Result<(), TopicStorageError> {
        let topic_patterns: Vec<String> = topic_filter.split("/").map(String::from).collect();
        let map = self.topic_tree.clone();
        let tenant_topic_root_rwlock = map.read();
        let tenant_topic_root_optional = tenant_topic_root_rwlock.get(&tenant_id);
        if let Some(tenant_topic_root) = tenant_topic_root_optional {
            let result = Self::recursion_clean_retain_publish_packet(
                tenant_topic_root.clone(),
                topic_patterns,
            );
            if let Err(err) = result {
                warn!(
                    "clean retain publish packet from the topic tree error: {}",
                    err
                );
                Err(err)
            } else {
                let mut retain_message_recorder = self.retain_message_recorder.write();
                let retain_message_recorder_optional = retain_message_recorder.get_mut(&tenant_id);
                if let Some(retain_message_recorder) = retain_message_recorder_optional {
                    retain_message_recorder.remove(topic_filter);
                }
                Ok(())
            }
        } else {
            Err(TopicStorageError::TenantNotFound(tenant_id))
        }
    }

    fn recursion_get_retain_packet(
        topic_node: Arc<RwLock<TopicStorageNode>>,
        mut topic_patterns: Vec<String>,
    ) -> Vec<Arc<Packet>> {
        let mut result: Vec<Arc<Packet>> = vec![];
        if !topic_patterns.is_empty() {
            let topic_pattern = &topic_patterns[0];
            if topic_pattern == &"#".to_string() {
                result.append(&mut Self::collect_retain_subtree(topic_node));
            } else if topic_pattern == &"+".to_string() {
                for sub in topic_node.write().leaves.read().iter() {
                    let topic_patterns_rest = topic_patterns.clone().drain(1..).collect();
                    result.append(&mut Self::recursion_get_retain_packet(
                        sub.1.clone(),
                        topic_patterns_rest,
                    ));
                }
            } else {
                let topic_node_next = topic_node.write().get_leaf(topic_pattern.to_string());
                if let Some(topic_node_next) = topic_node_next {
                    let topic_patterns_rest = topic_patterns.drain(1..).collect();
                    result.append(&mut Self::recursion_get_retain_packet(
                        topic_node_next,
                        topic_patterns_rest,
                    ));
                }
            }
        } else {
            let topic_node = topic_node.read();
            if let Some(p) = &topic_node.retain_publish_packet {
                result.append(&mut vec![p.clone()])
            }
        }
        result
    }

    fn collect_retain_subtree(topic_node: Arc<RwLock<TopicStorageNode>>) -> Vec<Arc<Packet>> {
        let (retain_packet, leaves) = {
            let node = topic_node.read();
            let retain_packet = node.retain_publish_packet.clone();
            let leaves = node.leaves.read().values().cloned().collect::<Vec<_>>();
            (retain_packet, leaves)
        };

        let mut result: Vec<Arc<Packet>> = vec![];
        if let Some(packet) = retain_packet {
            result.push(packet);
        }
        for leaf in leaves {
            result.append(&mut Self::collect_retain_subtree(leaf));
        }
        result
    }

    pub fn get_retain_publish_packet(
        &self,
        tenant_id: String,
        topic_filter: String,
    ) -> Result<Vec<Arc<Packet>>, TopicStorageError> {
        if !test_topic(&topic_filter) {
            return Err(TopicStorageError::InvalidTopicFilter(topic_filter));
        }

        let topic_patterns: Vec<String> = topic_filter.split("/").map(String::from).collect();
        let map = self.topic_tree.clone();
        let tenant_topic_root_rwlock = map.read();
        let tenant_topic_root_optional = tenant_topic_root_rwlock.get(&tenant_id);
        if let Some(tenant_topic_root) = tenant_topic_root_optional {
            let retain_packets =
                Self::recursion_get_retain_packet(tenant_topic_root.clone(), topic_patterns);
            Ok(retain_packets)
        } else {
            Err(TopicStorageError::TenantNotFound(tenant_id))
        }
    }

    // register retain publish packet to the topic tree
    pub fn register_retain_publish_packet(
        &self,
        tenant_id: String,
        source_client_identifier: String,
        publish_packet: &Packet,
    ) -> Result<(), TopicStorageError> {
        if let Packet::Publish(publish_packet) = publish_packet {
            let topic_filter = publish_packet.topic_name.clone();
            if !test_topic(&publish_packet.topic_name) {
                return Err(TopicStorageError::InvalidTopicFilter(topic_filter));
            }

            let topic_patterns: Vec<String> = topic_filter.split("/").map(String::from).collect();
            let map = self.topic_tree.clone();
            let tenant_topic_root_rwlock = map.read();
            let tenant_topic_root_optional = tenant_topic_root_rwlock.get(&tenant_id);
            if let Some(tenant_topic_root) = tenant_topic_root_optional {
                let result = Self::recursion_retain_publish_packet(
                    tenant_topic_root.clone(),
                    topic_patterns,
                    Packet::Publish(publish_packet.clone()),
                );
                if let Err(e) = result {
                    Err(e)
                } else {
                    // Update retain recorder
                    let mut retain_message_recorder = self.retain_message_recorder.write();
                    let retain_message_recorder_optional =
                        retain_message_recorder.get_mut(&tenant_id);
                    if let Some(retain_message_recorder_item) = retain_message_recorder_optional {
                        let qos = publish_packet.qos;
                        retain_message_recorder_item.insert(
                            publish_packet.topic_name.clone(),
                            (source_client_identifier, qos),
                        );
                    }
                    //
                    Ok(())
                }
            } else {
                Err(TopicStorageError::TenantNotFound(tenant_id))
            }
        } else {
            Ok(())
        }
    }

    // get all tenant names
    pub fn get_tenant_names(&self) -> Vec<String> {
        let map = self.topic_tree.clone();
        let tenant_topic_root_rwlock = map.read();
        tenant_topic_root_rwlock.keys().map(String::from).collect()
    }
}

#[derive(Serialize, Deserialize)]
struct SerializableTopicStorageNode {
    topic_parttern: String,
    subscriptions: HashMap<String, Subscription>,
    #[serde(default, deserialize_with = "deserialize_optional_retained_packet")]
    retain_publish_packet: Option<Packet>,
    leaves: HashMap<String, SerializableTopicStorageNode>,
}

fn deserialize_optional_retained_packet<'de, D>(deserializer: D) -> Result<Option<Packet>, D::Error>
where
    D: Deserializer<'de>,
{
    let value = Option::<serde_json::Value>::deserialize(deserializer)?;
    let Some(value) = value else {
        return Ok(None);
    };

    let bytes = serde_json::to_vec(&value).map_err(serde::de::Error::custom)?;
    deserialize_stored_packet(&bytes)
        .map(Some)
        .map_err(serde::de::Error::custom)
}

#[derive(Serialize, Deserialize)]
struct SerializableTopicStorage {
    retain_message_recorder: HashMap<String, HashMap<String, (String, u8)>>,
    topic_info_recorder: HashMap<String, HashMap<String, u8>>,
    topic_tree: HashMap<String, SerializableTopicStorageNode>,
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use yedmq_mqtt::{
        v3::{
            fixed_header::FixHeader,
            publish::{Payload, PublishPacket, VariableHeader},
        },
        MqttPacketV3, PacketType,
    };

    use super::*;
    use bytes::Bytes;
    use std::thread;

    fn build_retain_publish_packet(topic_name: &str) -> Packet {
        let fix_header = FixHeader {
            packet_type: PacketType::PUBLISH,
            qos: Some(1),
            retain: Some(true),
            dup: Some(1),
            remaining_length: 8,
        };
        let variable_header = VariableHeader {
            topic_name: topic_name.to_string(),
            packet_identifier: Some(0x10),
        };

        let payload = Payload {
            payload: Bytes::copy_from_slice(vec![0x01].as_slice()),
        };

        let publish_packet = PublishPacket {
            fix_header,
            variable_header,
            payload,
        };

        Packet::from(MqttPacketV3::Publish(publish_packet))
    }

    #[test]
    fn serializable_topic_storage_node_reads_legacy_mqtt3_retained_packet() {
        let legacy_packet = MqttPacketV3::Publish(
            yedmq_mqtt::v3::publish::PublishPacketBuilder::new(
                "legacy/retain".to_string(),
                Bytes::from_static(b"payload"),
            )
            .qos(1)
            .packet_identifier(9)
            .retain(true)
            .build(),
        );
        let value = serde_json::json!({
            "topic_parttern": "legacy",
            "subscriptions": {},
            "retain_publish_packet": legacy_packet,
            "leaves": {}
        });

        let node: SerializableTopicStorageNode =
            serde_json::from_value(value).expect("deserialize legacy retained packet");

        match node.retain_publish_packet {
            Some(Packet::Publish(publish)) => {
                assert_eq!(publish.topic_name, "legacy/retain");
                assert_eq!(publish.payload, Bytes::from_static(b"payload"));
                assert_eq!(publish.qos, 1);
                assert_eq!(publish.packet_identifier, Some(9));
                assert!(publish.retain);
            }
            other => panic!("expected retained publish packet, got {other:?}"),
        }
    }

    #[test]
    fn when_subscribe_same_topic_from_other_node_should_update_subscription() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            tenant_name.clone(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let _ = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());

        let _ = topic_storage.subscribe(
            tenant_name.clone(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let _ = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
    }

    #[test]
    fn test_add_subscription_and_get_subscriptions() {
        let topic_node = TopicStorageNode {
            topic_parttern: "a".to_string(),
            subscriptions: RwLock::new(HashMap::new()),
            leaves: Arc::new(RwLock::new(HashMap::new())),
            retain_publish_packet: None,
        };

        topic_node.add_subscription(Subscription {
            client_identifier: "1".to_string(),
            qos: 0,
            no_local: false,
            retain_as_published: false,
        });
        topic_node.add_subscription(Subscription {
            client_identifier: "2".to_string(),
            qos: 0,
            no_local: false,
            retain_as_published: false,
        });
        topic_node.add_subscription(Subscription {
            client_identifier: "3".to_string(),
            qos: 0,
            no_local: false,
            retain_as_published: false,
        });

        let subscriptions = topic_node.get_subscriptions();
        assert_eq!(subscriptions.len(), 3);
    }

    #[test]
    fn test_find_or_create_leaf() {
        let topic_node = TopicStorageNode {
            topic_parttern: "a".to_string(),
            subscriptions: RwLock::new(HashMap::new()),
            leaves: Arc::new(RwLock::new(HashMap::new())),
            retain_publish_packet: None,
        };

        let new_topic_node = topic_node.find_or_create_leaf("b".to_string());
        assert_eq!(new_topic_node.read().topic_parttern, "b");

        assert!(topic_node.leaves.read().contains_key("b"));
    }

    #[test]
    fn test_multiple_thread() {
        let topic_node = TopicStorageNode {
            topic_parttern: "a".to_string(),
            subscriptions: RwLock::new(HashMap::new()),
            leaves: Arc::new(RwLock::new(HashMap::new())),
            retain_publish_packet: None,
        };

        let topic_node_arc = Arc::new(RwLock::new(topic_node));
        let topic_node_arc_clone = topic_node_arc.clone();
        let topic_node_arc_read_clone = topic_node_arc.clone();
        let thread_1 = thread::spawn(move || {
            let new_topic_node = topic_node_arc.write().find_or_create_leaf("b".to_string());
            assert_eq!(new_topic_node.read().topic_parttern, "b");
        });
        let thread_3 = thread::spawn(move || {
            let subscriptions = topic_node_arc_read_clone.read().get_subscriptions();
            assert_eq!(subscriptions.len(), 0);
        });
        let thread_2 = thread::spawn(move || {
            let new_topic_node = topic_node_arc_clone
                .write()
                .find_or_create_leaf("c".to_string());
            assert_eq!(new_topic_node.read().topic_parttern, "c");
        });

        let _ = thread_1.join();
        let _ = thread_2.join();
        let _ = thread_3.join();
    }

    #[test]
    fn test_subscribe_topic() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(tenant_name, "clientA".to_string(), "a/b/c".to_string(), 0);
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
        assert_eq!(clients.unwrap().len(), 1);
        let topic_info_recorder = topic_storage.topic_info_recorder.read();
        assert_eq!(topic_info_recorder.len(), 2); // default tenant + created tenant

        assert!(topic_info_recorder
            .get("hello")
            .unwrap()
            .contains_key(&generate_key("clientA", "a/b/c")),);
        assert_eq!(
            topic_info_recorder
                .get("hello")
                .unwrap()
                .get(&generate_key("clientA", "a/b/c"))
                .unwrap(),
            &0_u8
        );
    }

    #[test]
    fn test_unsubscribe_topic() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            tenant_name.clone(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let _ = topic_storage.unsubscribe(&tenant_name, "clientA", "a/b/c");
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
        assert_eq!(clients.unwrap().len(), 0);

        let topic_info_recorder = topic_storage.topic_info_recorder.read();
        assert_eq!(topic_info_recorder.len(), 2); // default tenant + created tenant

        assert!(!topic_info_recorder
            .get("hello")
            .unwrap()
            .contains_key(&generate_key("clientA", "a/b/c")),);
    }

    #[test]
    fn test_sharp_wildcard_subscriptions() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/b/#".to_string(),
            0,
        );
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
        assert_eq!(clients.unwrap().len(), 1);
    }

    #[test]
    fn test_plus_wildcard_subscriptions() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/+/c".to_string(),
            0,
        );
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
        assert_eq!(clients.unwrap().len(), 1);
    }

    #[test]
    fn test_multiple_subscription() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientB".to_string(),
            "a/b/#".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientC".to_string(),
            "a/+/+".to_string(),
            0,
        );
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
        assert_eq!(clients.unwrap().len(), 3);
    }

    #[test]
    fn test_mix_wildcard_subscription() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientB".to_string(),
            "a/+/#".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientC".to_string(),
            "a/+/+".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientD".to_string(),
            "a/+/+/+".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientE".to_string(),
            "a/+".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientF".to_string(),
            "a/+/c".to_string(),
            0,
        );
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c/d".to_string());
        let clients = clients.unwrap();
        assert_eq!(clients.len(), 2);
        assert_eq!(clients.clone()[0].client_identifier, "clientB");
        assert_eq!(clients.clone()[1].client_identifier, "clientD");
    }

    #[test]
    fn test_invalid_topic_filter() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/#/c".to_string(),
            0,
        );

        let result = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "sport+".to_string(),
            0,
        );

        match result.unwrap_err() {
            TopicStorageError::InvalidTopicFilter(msg) => {
                if msg != "sport+" {
                    panic!("Unexpected error message: {}", msg);
                }
            }
            _ => panic!("Expected InvalidTopicFilter error"),
        }

        let result = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "sport+".to_string(),
            0,
        );

        match result.unwrap_err() {
            TopicStorageError::InvalidTopicFilter(msg) => {
                if msg != "sport+" {
                    panic!("Unexpected error message: {}", msg);
                }
            }
            _ => panic!("Expected InvalidTopicFilter error"),
        }
    }

    #[test]
    fn test_topic_subscription_multiple_thread() {
        let topic_storage = Arc::new(RwLock::new(TopicStorage::new()));
        let tenant_name = "hello".to_string();
        topic_storage.write().create_tenant(&tenant_name);
        let topic_storage_t_1 = topic_storage.clone();
        let topic_storage_t_2 = topic_storage.clone();
        let topic_storage_t_3 = topic_storage.clone();
        let thread_1 = thread::spawn(move || {
            let _ = topic_storage_t_1.write().subscribe(
                "hello".to_string(),
                "clientA".to_string(),
                "a/b/c".to_string(),
                0,
            );
            let _ = topic_storage_t_1.write().subscribe(
                "hello".to_string(),
                "clientB".to_string(),
                "a/+/#".to_string(),
                0,
            );
            let _ = topic_storage_t_1.write().subscribe(
                "hello".to_string(),
                "clientC".to_string(),
                "a/+/+".to_string(),
                0,
            );
        });
        let thread_3 = thread::spawn(move || {
            let _ = topic_storage_t_2.write().subscribe(
                "hello".to_string(),
                "clientD".to_string(),
                "a/+/+/+".to_string(),
                0,
            );
            let _ = topic_storage_t_2.write().subscribe(
                "hello".to_string(),
                "clientE".to_string(),
                "a/+".to_string(),
                0,
            );
        });
        let thread_2 = thread::spawn(move || {
            let _ = topic_storage_t_3.write().subscribe(
                "hello".to_string(),
                "clientF".to_string(),
                "a/+/c".to_string(),
                0,
            );
        });

        let _ = thread_1.join();
        let _ = thread_2.join();
        let _ = thread_3.join();

        let clients = topic_storage
            .write()
            .get_subscriptions("hello".to_string(), "a/b/c/d".to_string());
        let clients = clients.unwrap();
        assert_eq!(clients.len(), 2);
        assert_eq!(clients.clone()[0].client_identifier, "clientB");
        assert_eq!(clients.clone()[1].client_identifier, "clientD");
    }

    #[test]
    fn test_mutiple_subscription_the_same_topic_only_one_subscription() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let _ = topic_storage.subscribe(
            "hello".to_string(),
            "clientA".to_string(),
            "a/b/c".to_string(),
            0,
        );
        let clients = topic_storage.get_subscriptions("hello".to_string(), "a/b/c".to_string());
        assert_eq!(clients.unwrap().len(), 1);
    }

    #[test]
    fn test_retain_message() {
        let publish_packet = build_retain_publish_packet("a/b");

        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);
        topic_storage
            .register_retain_publish_packet(
                "hello".to_string(),
                "client_a".to_string(),
                &publish_packet,
            )
            .unwrap();
        let retain_packet =
            topic_storage.get_retain_publish_packet("hello".to_string(), "a/b".to_string());
        assert_eq!(1, retain_packet.unwrap().len());

        let retain_packet =
            topic_storage.get_retain_publish_packet("hello".to_string(), "a/+".to_string());
        assert_eq!(1, retain_packet.unwrap().len());

        let retain_packet =
            topic_storage.get_retain_publish_packet("hello".to_string(), "a/#".to_string());
        assert_eq!(1, retain_packet.unwrap().len());

        let retain_packet =
            topic_storage.get_retain_publish_packet("hello".to_string(), "a".to_string());
        assert_eq!(0, retain_packet.unwrap().len());
    }

    #[test]
    fn test_retain_message_sharp_wildcard_should_include_current_node() {
        let topic_storage = TopicStorage::new();
        let tenant_name = "hello".to_string();
        topic_storage.create_tenant(&tenant_name);

        let root_packet = build_retain_publish_packet("a");
        let child_packet = build_retain_publish_packet("a/b");

        topic_storage
            .register_retain_publish_packet(
                "hello".to_string(),
                "client_a".to_string(),
                &root_packet,
            )
            .unwrap();
        topic_storage
            .register_retain_publish_packet(
                "hello".to_string(),
                "client_a".to_string(),
                &child_packet,
            )
            .unwrap();

        let retain_packet =
            topic_storage.get_retain_publish_packet("hello".to_string(), "a/#".to_string());
        let retain_packet = retain_packet.unwrap();
        assert_eq!(2, retain_packet.len());

        let mut topics = retain_packet
            .iter()
            .filter_map(|packet| match &**packet {
                Packet::Publish(p) => Some(p.topic_name.clone()),
                _ => None,
            })
            .collect::<Vec<String>>();
        topics.sort();
        assert_eq!(topics, vec!["a".to_string(), "a/b".to_string()]);
    }
}
