[package]
name = "samoye-plugins-acl-file"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
samoye-plugin = { path = "../../plugin" }
samoye-mqtt = { path = "../../mqtt" }
anyhow = "1.0"
log = "0.4"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0"