[mqtt]
sys_topic_interval_secs = 10
inflight_retry_interval_secs = 10
default_authentication = "allow"
default_authorization = "allow"
max_message_size = 268435456

[session]
qos_expired_secs = 10
packet_resend_interval_secs = 10
session_clock_path = "./clock"

[plugin]
dir = "./plugins"

[log]
level = "warning"

[listener.api]
external = "0.0.0.0:3456"

[listener.tcp]
external = "0.0.0.0:1883"

[listener.tcp_tls]
external = "0.0.0.0:8883"
cacert_file = ""
cert_file = ""
key_file = ""

[listener.ws]
external = "0.0.0.0:8083"

[listener.wss]
external = "0.0.0.0:8084"
cacert_file = ""
cert_file = ""
key_file = ""

[listener.api.auth]
users = [
    { username = "admin", password = "password" }
]

[cluster]
cluster_name = "YedMQ"
node_id = 1001
heartbeat_interval = 10
store_dir = "./store"
nodes = [
    { id = 1001, rpc_address = "0.0.0.0:3457", api_address = "0.0.0.0:3456" }
]
session_ttl = 10

[cluster.rpc]
external = "0.0.0.0:3457"
