[mqtt]
sys_topic_interval_secs = 10
default_authentication = "allow"
default_authorization = "allow"

[session]
qos_expired_secs = 10
packet_resend_interval_secs = 10

[plugin]
dir = "/etc/yedmq/plugins"

[log]
level = "warning"

[listener.api]
external = "0.0.0.0:3456"

[listener.tcp]
external = "0.0.0.0:1883"

[listener.tcp_tls]
external = "0.0.0.0:8883"
cacert_file = ""
cert_file = ""
key_file = ""

[listener.ws]
external = "0.0.0.0:8083"

[listener.wss]
external = "0.0.0.0:8084"
cacert_file = ""
cert_file = ""
key_file = ""